const DASHBOARD_PERMISSION = {
    READ: 'DASHBOARD_READ',
}

const CUSTOMER_PERMISSION = {
    READ: 'CUSTOMER_READ',
    WRITE: 'CUSTOMER_WRITE',
}

export {
    DASHBOARD_PERMISSION,
    CUSTOMER_PERMISSION
}
